// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMsJ9XwPelsSw2anSwUgtrofy4BS-sqA',
    appId: '1:207078450231:web:228d0aa0141aba10e3cbb2',
    messagingSenderId: '207078450231',
    projectId: 'university-73b1a',
    authDomain: 'university-73b1a.firebaseapp.com',
    storageBucket: 'university-73b1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbysptjr2YzcoK3-LVxoUGZT1V59t0nw',
    appId: '1:207078450231:android:9d6870edb6b51fc5e3cbb2',
    messagingSenderId: '207078450231',
    projectId: 'university-73b1a',
    storageBucket: 'university-73b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0EpoD59sMiVE5eoGubGbr4o9Ai1FIk4',
    appId: '1:207078450231:ios:afa15c7101262816e3cbb2',
    messagingSenderId: '207078450231',
    projectId: 'university-73b1a',
    storageBucket: 'university-73b1a.appspot.com',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq0EpoD59sMiVE5eoGubGbr4o9Ai1FIk4',
    appId: '1:207078450231:ios:afa15c7101262816e3cbb2',
    messagingSenderId: '207078450231',
    projectId: 'university-73b1a',
    storageBucket: 'university-73b1a.appspot.com',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMsJ9XwPelsSw2anSwUgtrofy4BS-sqA',
    appId: '1:207078450231:web:6c08454789ada29ce3cbb2',
    messagingSenderId: '207078450231',
    projectId: 'university-73b1a',
    authDomain: 'university-73b1a.firebaseapp.com',
    storageBucket: 'university-73b1a.appspot.com',
  );
}
